### PR TITLE
review fixes

### PR DESCRIPTION
**Pull request by valer1435**
### **User description**
fixes

___

### **PR Type**
Enhancement

___

### **Description**
- Refactored GitHub provider initialization and comment parsing in `main.py` to improve encapsulation and modularity.
- Added null checks in `github_issue_provider.py` to prevent errors when issue or comment bodies are missing.
- Introduced error handling in `issue_agent.py` to log and handle exceptions during issue request processing.
- Added error handling in `data_loader.py` to print and continue execution when HTML loading fails.
- Normalized reranker scores in `reranker.py` to ensure consistent ranking of chunks.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>main.py</strong><dd><code>Refactor GitHub provider initialization and comment parsing</code></dd></summary>
<hr>

repo_copilot/github-integration/main.py
<li>Added <code>pr_config_path</code> attribute to the class.<br> <li> Introduced new methods <code>_get_issue_provider</code> and <code>_get_pr_provider</code> to <br>encapsulate provider initialization.<br> <li> Modified <code>_parse_comment</code> method to accept a provider and handle <br>issue-specific logic.<br> <li> Updated <code>handle_pr</code> and <code>handle_issue</code> methods to use the new provider <br>methods.<br>

</details>
    

  </td>
  <td><a href="https://github.com/valer1435/RepoPilot/pull/32/files#diff-41baed3c80a361cce5655939ab39ae06a6d63d820e94d0e83ccdf10a4becd5e0">+23/-11</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>reranker.py</strong><dd><code>Normalize reranker scores for consistent ranking</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

repo_copilot/rag/issue/rag_app/retrieval/reranker.py
<li>Normalized the scores returned by the reranker to ensure they are <br>within a consistent range.<br>

</details>
    

  </td>
  <td><a href="https://github.com/valer1435/RepoPilot/pull/32/files#diff-4c21b97db8dedd9034e5cb92ead322e75d282934b709e968d55822a1fc664da3">+4/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Bug fix
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>github_issue_provider.py</strong><dd><code>Add null checks for issue and comment bodies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

repo_copilot/rag/issue/github_issue_provider.py
<li>Added null checks for <code>self.issue</code> and <code>self.issue.body</code> before appending <br>to <code>all_comments</code>.<br> <li> Added null checks for each comment and its body before appending to <br><code>all_comments</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/valer1435/RepoPilot/pull/32/files#diff-1bf16c16ae97853c6b41dbf6485650031f8de2cdcc40f293758a45fdbc6792f3">+4/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Error handling
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>issue_agent.py</strong><dd><code>Add error handling for issue request processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

repo_copilot/rag/issue/issue_agent.py
<li>Added exception handling around the <code>IssueQuestions.run()</code> call to log <br>errors and return <code>False</code> on failure.<br>

</details>
    

  </td>
  <td><a href="https://github.com/valer1435/RepoPilot/pull/32/files#diff-7c9ac7e334b719714dc9a1a2c53ef175c8508e9a5df240da004db96aca8ee6ac">+5/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>data_loader.py</strong><dd><code>Add error handling for HTML loading</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

repo_copilot/rag/issue/rag_app/data_loader.py
<li>Added exception handling around the <code>load_data</code> call to print errors and <br>continue execution.<br>

</details>
    

  </td>
  <td><a href="https://github.com/valer1435/RepoPilot/pull/32/files#diff-081efac4af3029db5daf2d27dc9499f073320fa4fe107523b02db69f9fdc0f83">+6/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by valer1435** [comment]
@RepoPilotAssistant /help

**Comment by valer1435** [comment]
@RepoPilotAssistant /help

**Comment by RepoPilotAssistant** [comment]
## PR Agent Walkthrough 🤖

Welcome to the PR Agent, an AI-powered tool for automated pull request analysis, feedback, suggestions and more.

Here is a list of tools you can use to interact with the PR Agent:
<table><tr align='left'><th align='left'>Tool</th><th align='left'>Description</th><th align='left'>Trigger Interactively :gem:</th></tr>
<tr><td align='left'>

<strong>[DESCRIBE](https://pr-agent-docs.codium.ai/tools/describe/)</strong></td>
<td>Generates PR description - title, type, summary, code walkthrough and labels</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[REVIEW](https://pr-agent-docs.codium.ai/tools/review/)</strong></td>
<td>Adjustable feedback about the PR, possible issues, security concerns, review effort and more</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE](https://pr-agent-docs.codium.ai/tools/improve/)</strong></td>
<td>Code suggestions for improving the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[UPDATE CHANGELOG](https://pr-agent-docs.codium.ai/tools/update_changelog/)</strong></td>
<td>Automatically updates the changelog</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ADD DOCS](https://pr-agent-docs.codium.ai/tools/documentation/) 💎</strong></td>
<td>Generates documentation to methods/functions/classes that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[TEST](https://pr-agent-docs.codium.ai/tools/test/) 💎</strong></td>
<td>Generates unit tests for a specific component, based on the PR code change</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE COMPONENT](https://pr-agent-docs.codium.ai/tools/improve_component/) 💎</strong></td>
<td>Code suggestions for a specific component that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ANALYZE](https://pr-agent-docs.codium.ai/tools/analyze/) 💎</strong></td>
<td>Identifies code components that changed in the PR, and enables to interactively generate tests, docs, and code suggestions for each component</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ASK](https://pr-agent-docs.codium.ai/tools/ask/)</strong></td>
<td>Answering free-text questions about the PR</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[GENERATE CUSTOM LABELS](https://pr-agent-docs.codium.ai/tools/custom_labels/) 💎</strong></td>
<td>Generates custom labels for the PR, based on specific guidelines defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CI FEEDBACK](https://pr-agent-docs.codium.ai/tools/ci_feedback/) 💎</strong></td>
<td>Generates feedback and analysis for a failed CI job</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CUSTOM PROMPT](https://pr-agent-docs.codium.ai/tools/custom_prompt/) 💎</strong></td>
<td>Generates custom suggestions for improving the PR code, derived only from a specific guidelines prompt defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[SIMILAR ISSUE](https://pr-agent-docs.codium.ai/tools/similar_issues/)</strong></td>
<td>Automatically retrieves and presents similar issues</td>
<td>

[*]
</td></tr></table>



(1) Note that each tool be [triggered automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools-for-pr-actions) when a new PR is opened, or called manually by [commenting on a PR](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#online-usage).

(2) Tools marked with [*] require additional parameters to be passed. For example, to invoke the `/ask` tool, you need to comment on a PR: `/ask "<question content>"`. See the relevant documentation for each tool for more details.

**Comment by valer1435** [comment]
@RepoPilotAssistant /describe

**Comment by RepoPilotAssistant** [comment]
**[PR Description](https://github.com/valer1435/RepoPilot/pull/32)** updated to latest commit (https://github.com/valer1435/RepoPilot/commit/8354afb79f27eb88fbd2e165c89618208bb2f361)

**Comment by valer1435** [comment]
@RepoPilotAssistant /review

**Comment by RepoPilotAssistant** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, because the PR introduces significant refactoring and new error handling logic across multiple files, requiring careful review to ensure correctness and maintainability.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> In `main.py`, the `_parse_comment` method assumes that `notification['subject']['type']` will always be present and correctly set. If this key is missing or incorrect, it could lead to unexpected behavior.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> In `reranker.py`, normalizing scores in a loop could be optimized by using list comprehensions or built-in functions for better performance.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>repo_copilot/github-integration/main.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add a check for the presence of `notification['subject']['type']` in the `_parse_comment` method to prevent potential KeyError. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/32/files#diff-41baed3c80a361cce5655939ab39ae06a6d63d820e94d0e83ccdf10a4becd5e0R84'>if notification['subject']['type'] == 'Issue' and len(provider.issue_comments) == 0 and comment[</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/rag/issue/rag_app/retrieval/reranker.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Optimize the normalization of scores by using `min()` and `max()` functions directly in the list comprehension for better performance. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/32/files#diff-4c21b97db8dedd9034e5cb92ead322e75d282934b709e968d55822a1fc664da3R20'>normalized_scores = [(score - min_score) / (max_score - min_score) for score in scores]</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/rag/issue/issue_agent.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider logging the exception type along with the error message in `handle_request` for better debugging. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/32/files#diff-7c9ac7e334b719714dc9a1a2c53ef175c8508e9a5df240da004db96aca8ee6acR33'>get_logger().error(f"Error handling issue request: {e}")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/rag/issue/github_issue_provider.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Ensure that `self.issue` and `self.issue.body` are not None before accessing their attributes to avoid potential AttributeError. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/32/files#diff-1bf16c16ae97853c6b41dbf6485650031f8de2cdcc40f293758a45fdbc6792f3R180'>if self.issue and self.issue.body:</a></td></tr></table><hr>

</details>

**Pull request merged**
