### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by valer1435**

### CODE REVIEW

**Comment by valer1435** [comment]
@RepoPilotAssistant /help

**Comment by valer1435** [comment]
@RepoPilotAssistant /help

**Comment by RepoPilotAssistant** [comment]
## PR Agent Walkthrough 🤖

Welcome to the PR Agent, an AI-powered tool for automated pull request analysis, feedback, suggestions and more.

Here is a list of tools you can use to interact with the PR Agent:
<table><tr align='left'><th align='left'>Tool</th><th align='left'>Description</th><th align='left'>Trigger Interactively :gem:</th></tr>
<tr><td align='left'>

<strong>[DESCRIBE](https://pr-agent-docs.codium.ai/tools/describe/)</strong></td>
<td>Generates PR description - title, type, summary, code walkthrough and labels</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[REVIEW](https://pr-agent-docs.codium.ai/tools/review/)</strong></td>
<td>Adjustable feedback about the PR, possible issues, security concerns, review effort and more</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE](https://pr-agent-docs.codium.ai/tools/improve/)</strong></td>
<td>Code suggestions for improving the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[UPDATE CHANGELOG](https://pr-agent-docs.codium.ai/tools/update_changelog/)</strong></td>
<td>Automatically updates the changelog</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ADD DOCS](https://pr-agent-docs.codium.ai/tools/documentation/) 💎</strong></td>
<td>Generates documentation to methods/functions/classes that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[TEST](https://pr-agent-docs.codium.ai/tools/test/) 💎</strong></td>
<td>Generates unit tests for a specific component, based on the PR code change</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE COMPONENT](https://pr-agent-docs.codium.ai/tools/improve_component/) 💎</strong></td>
<td>Code suggestions for a specific component that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ANALYZE](https://pr-agent-docs.codium.ai/tools/analyze/) 💎</strong></td>
<td>Identifies code components that changed in the PR, and enables to interactively generate tests, docs, and code suggestions for each component</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ASK](https://pr-agent-docs.codium.ai/tools/ask/)</strong></td>
<td>Answering free-text questions about the PR</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[GENERATE CUSTOM LABELS](https://pr-agent-docs.codium.ai/tools/custom_labels/) 💎</strong></td>
<td>Generates custom labels for the PR, based on specific guidelines defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CI FEEDBACK](https://pr-agent-docs.codium.ai/tools/ci_feedback/) 💎</strong></td>
<td>Generates feedback and analysis for a failed CI job</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CUSTOM PROMPT](https://pr-agent-docs.codium.ai/tools/custom_prompt/) 💎</strong></td>
<td>Generates custom suggestions for improving the PR code, derived only from a specific guidelines prompt defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[SIMILAR ISSUE](https://pr-agent-docs.codium.ai/tools/similar_issues/)</strong></td>
<td>Automatically retrieves and presents similar issues</td>
<td>

[*]
</td></tr></table>



(1) Note that each tool be [triggered automatically](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#github-app-automatic-tools-when-a-new-pr-is-opened) when a new PR is opened, or called manually by [commenting on a PR](https://pr-agent-docs.codium.ai/usage-guide/automations_and_usage/#online-usage).

(2) Tools marked with [*] require additional parameters to be passed. For example, to invoke the `/ask` tool, you need to comment on a PR: `/ask "<question content>"`. See the relevant documentation for each tool for more details.

**Comment by valer1435** [comment]
@RepoPilotAssistant /review

**Comment by RepoPilotAssistant** [comment]
## PR Reviewer Guide 🔍

<table>
<tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 4 🔵🔵🔵🔵⚪</td></tr>
<tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
<tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-b2d7287c6532066bb60216d685f81155fb0d3cb31b1561e031df8aaf0e1843c3R7-R7'><strong>Security Concern</strong></a><br>The use of `load_dotenv()` without specifying a `.env` file path could lead to loading unintended environment variables from a `.env` file in the current directory.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-b2d7287c6532066bb60216d685f81155fb0d3cb31b1561e031df8aaf0e1843c3R8-R9'><strong>Hardcoded Configuration</strong></a><br>The use of hardcoded configuration file paths (`'config.yml'`) could lead to issues if the file is not present or named differently in different environments.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-b2d7287c6532066bb60216d685f81155fb0d3cb31b1561e031df8aaf0e1843c3R13-R13'><strong>Hardcoded File Path</strong></a><br>The use of a hardcoded file path (`'../../data/labeled_questions.json'`) could lead to issues if the file is not present or named differently in different environments.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-b2d7287c6532066bb60216d685f81155fb0d3cb31b1561e031df8aaf0e1843c3R15-R15'><strong>Hardcoded File Path</strong></a><br>The use of a hardcoded file path (`'res1.json'`) could lead to issues if the file is not present or named differently in different environments.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-54ce5a3fc8bd32ffc3d045dc4088eef69fa7dbdae6589815d30ee69d45cc6cfeR5-R5'><strong>Hardcoded Configuration</strong></a><br>The use of hardcoded configuration file paths (`'config.yml'` and `'pr_agent.toml'`) could lead to issues if the file is not present or named differently in different environments.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-c5a0bc794f782ff6b0df4ed182a1365df7dccc4a3d840353f8d91ee56f147bbeR7-R7'><strong>Hardcoded Configuration</strong></a><br>The use of hardcoded configuration file paths (`'config.yml'` and `'pr_agent.toml'`) could lead to issues if the file is not present or named differently in different environments.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R5-R5'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R16-R16'><strong>Unused Imports</strong></a><br>The import of `IssueAgent` from `repo_copilot.rag.issue.issue_agent` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R17-R17'><strong>Unused Imports</strong></a><br>The import of `RAGApp` from `repo_copilot.rag.issue.rag_app.rag` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R12-R12'><strong>Unused Imports</strong></a><br>The import of `Optional` from `typing` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R14-R14'><strong>Unused Imports</strong></a><br>The import of `PrGithubProvider` from `repo_copilot.rag.pr.PrGithubProvider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R15-R15'><strong>Unused Imports</strong></a><br>The import of `IssueGithubProvider` from `repo_copilot.rag.issue.github_issue_provider` is not used in the code.

<a href='https://github.com/valer1435/RepoPilot/pull/37/files#diff-f3a5dfa212e37d346a558326317408af3e5a2d650e137235366a938fd5ef9eb3R0'><strong></strong></a><br>

</td></tr>
</table>

**Pull request merged**
