### PR TITLE
Pr reviewer

### PR DESCRIPTION
**Pull request by valer1435**
Major refactoring & new features were added

### CODE REVIEW

**Comment by valer1435** [comment]
@RepoPilotAssistant /review

**Comment by RepoPilotAssistant** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

5, because the PR involves major refactoring and new features, including significant changes to multiple files and the addition of new classes and methods. The complexity and scope of the changes require thorough review and testing.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

No


</td></tr>
<tr><td rowspan=3> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Possible Bug:</strong> The `pool` method in `RepoPilot` class is calling `asyncio.run(self._polling_loop())`, which is not recommended for use in asynchronous code. Instead, `asyncio.create_task` should be used to run the polling loop in the background.</td></tr>
<tr>
<td>

<strong>Performance Concern:</strong> The `_polling_loop` method in `RepoPilot` class has a while loop with `await asyncio.sleep(5)`, which could lead to high CPU usage if not properly managed. Consider using `asyncio.sleep` with a longer interval or implementing a more efficient polling mechanism.</td></tr>
<tr>
<td>

<strong>Code Duplication:</strong> The `_get_github_client` method in `IssueGithubProvider` class has similar logic to the `_get_github_client` method in `PrGithubProvider` class. Consider refactoring to avoid code duplication.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>repo_copilot/github-integration/main.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Use `asyncio.create_task` instead of `asyncio.run` to run the polling loop in the background. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/31/files#diff-41baed3c80a361cce5655939ab39ae06a6d63d820e94d0e83ccdf10a4becd5e0R123'>asyncio.run(self._polling_loop())</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/github-integration/main.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider using a more efficient polling mechanism or increasing the sleep interval to reduce CPU usage. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/31/files#diff-41baed3c80a361cce5655939ab39ae06a6d63d820e94d0e83ccdf10a4becd5e0R150'>await asyncio.sleep(5)</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/rag/issue/github_issue_provider.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Refactor the `_get_github_client` method to avoid code duplication with the `_get_github_client` method in `PrGithubProvider` class. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/31/files#diff-1bf16c16ae97853c6b41dbf6485650031f8de2cdcc40f293758a45fdbc6792f3R21'>self.github_client = self._get_github_client()</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>repo_copilot/rag/issue/github_issue_provider.py
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Ensure that the `get_notifications` method handles pagination correctly to avoid missing notifications. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/valer1435/RepoPilot/pull/31/files#diff-1bf16c16ae97853c6b41dbf6485650031f8de2cdcc40f293758a45fdbc6792f3R85'>notifications = self.github_client.get_user().get_notifications(since=since)</a></td></tr></table><hr>

</details>

**Comment by valer1435** [comment]
@RepoPilotAssistant /improve

**Comment by RepoPilotAssistant** [comment]
## PR Code Suggestions ✨

<table><thead><tr><td>Category</td><td align=left>Suggestion&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </td><td align=center>Score</td></tr><tbody><tr><td rowspan=2><strong>Best practice</strong></td>
<td>



<details><summary>Normalize scores before sorting chunks in <code>rerank</code> method</summary>

___


**The <code>rerank</code> method should ensure that the scores are normalized before sorting the chunks.**
    
[repo_copilot/rag/issue/rag_app/retrieval/reranker.py [14-20]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-4c21b97db8dedd9034e5cb92ead322e75d282934b709e968d55822a1fc664da3R14-R20)

```diff
 def rerank(self, query, chunks):
     # construct sentence pairs
     sentence_pairs = [[query, doc.node.text] for doc in chunks]
     scores = self.model.compute_score(sentence_pairs, max_length=1024)
+    min_score = min(scores)
+    max_score = max(scores)
+    normalized_scores = [(score - min_score) / (max_score - min_score) for score in scores]
     for i in range(len(chunks)):
-        chunks[i].score = scores[i]
+        chunks[i].score = normalized_scores[i]
     return sorted(chunks, key=lambda x: -x.score)[:self.top_k]
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 9</b></summary>

Why: The suggestion is crucial for ensuring fair and accurate ranking by normalizing scores before sorting, which is a best practice in ranking algorithms.

</details></details></td><td align=center>9

</td></tr><tr><td>



<details><summary>Ensure <code>load_dotenv()</code> only runs in development environments</summary>

___


**The <code>load_dotenv()</code> call should be placed inside a conditional block to ensure it only runs <br>in development environments. This prevents loading environment variables in production.**
    
[examples/fedot_example/fedot_example.py [5]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-54ce5a3fc8bd32ffc3d045dc4088eef69fa7dbdae6589815d30ee69d45cc6cfeR5-R5)

```diff
-load_dotenv()
+if os.getenv('ENVIRONMENT') == 'development':
+    load_dotenv()
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 7</b></summary>

Why: The suggestion is correct and improves the code by ensuring that environment variables are only loaded in development environments, which is a good practice.

</details></details></td><td align=center>7

</td></tr><tr><td rowspan=2><strong>Possible bug</strong></td>
<td>



<details><summary>Add error handling to <code>handle_request</code> method</summary>

___


**The <code>handle_request</code> method should include error handling to catch and log any exceptions <br>that occur during the execution of the <code>IssueQuestions</code> class.**
    
[repo_copilot/rag/issue/issue_agent.py [32-33]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-7c9ac7e334b719714dc9a1a2c53ef175c8508e9a5df240da004db96aca8ee6acR32-R33)

```diff
-await IssueQuestions(issue_url, ai_handler=self.ai_handler, rag_engine=self.rag_engine).run()
+try:
+    await IssueQuestions(issue_url, ai_handler=self.ai_handler, rag_engine=self.rag_engine).run()
+except Exception as e:
+    get_logger().error(f"Error handling issue request: {e}")
 return True
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 9</b></summary>

Why: The suggestion is crucial as it adds necessary error handling to catch and log exceptions, preventing potential crashes and improving the robustness of the code.

</details></details></td><td align=center>9

</td></tr><tr><td>



<details><summary>Add exception handling in <code>load_html</code> method to manage potential errors during data loading</summary>

___


**The `load_html` method should handle potential exceptions when loading data from URLs.**
    
[repo_copilot/rag/issue/rag_app/data_loader.py [46-51]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-081efac4af3029db5daf2d27dc9499f073320fa4fe107523b02db69f9fdc0f83R46-R51)

```diff
 def load_html(self, links, collection_name):
     loader = BeautifulSoupWebReader()
-    documents = loader.load_data(urls=links)
-    # Ingest directly into a vector db
-    self.vector_stores[collection_name]['pipeline'].run(documents=documents,
-                                                        show_progress=True)
+    try:
+        documents = loader.load_data(urls=links)
+        # Ingest directly into a vector db
+        self.vector_stores[collection_name]['pipeline'].run(documents=documents,
+                                                            show_progress=True)
+    except Exception as e:
+        print(f"Error loading HTML from links: {e}")
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 8</b></summary>

Why: The suggestion correctly identifies a potential issue with exception handling in the `load_html` method, which is crucial for robust error management during data loading.

</details></details></td><td align=center>8

</td></tr><tr><td rowspan=1><strong>Possible issue</strong></td>
<td>



<details><summary>Add checks to ensure issue and comments are not empty</summary>

___


**The <code>get_issue_as_prompt</code> method should include a check to ensure the issue and comments are <br>not empty before attempting to join them.**
    
[repo_copilot/rag/issue/github_issue_provider.py [178-183]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-1bf16c16ae97853c6b41dbf6485650031f8de2cdcc40f293758a45fdbc6792f3R178-R183)

```diff
-all_comments.append(f'Author: {self.issue.user.login}\nContent:\n{self.issue.body}')
+if self.issue and self.issue.body:
+    all_comments.append(f'Author: {self.issue.user.login}\nContent:\n{self.issue.body}')
 for i in self.issue_comments:
-    all_comments.append(f'Author: {i.user.login}\nContent:\n{i.body}')
+    if i and i.body:
+        all_comments.append(f'Author: {i.user.login}\nContent:\n{i.body}')
 return '\n\n'.join(all_comments)
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 8</b></summary>

Why: The suggestion is correct and addresses a potential issue by ensuring that the method does not attempt to join empty strings, which could lead to unexpected behavior.

</details></details></td><td align=center>8

</td></tr><tr><td rowspan=2><strong>Performance</strong></td>
<td>



<details><summary>Limit the number of pages to visit in <code>get_all_pages</code> to prevent infinite loops or excessive resource usage</summary>

___


**The <code>get_all_pages</code> function should limit the number of pages to visit to prevent infinite <br>loops or excessive resource usage.**
    
[repo_copilot/rag/issue/rag_app/data_loader.py [68-105]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-081efac4af3029db5daf2d27dc9499f073320fa4fe107523b02db69f9fdc0f83R68-R105)

```diff
-def get_all_pages(start_url):
+def get_all_pages(start_url, max_pages=100):
     base_url = get_domain(start_url)
     visited = set()
     to_visit = [start_url]
     pages = []
 
-    while to_visit:
+    while to_visit and len(pages) < max_pages:
         current_url = to_visit.pop(0)
         if current_url in visited:
             continue
 
         try:
             response = requests.get(current_url)
             response.raise_for_status()
         except requests.RequestException as e:
             print(f"Error fetching {current_url}: {e}")
             continue
 
         visited.add(current_url)
         pages.append(current_url)
 
         soup = BeautifulSoup(response.text, 'html.parser')
         for link in soup.find_all('a', href=True):
             full_url = urljoin(current_url, link['href'])
             if is_same_domain(full_url, base_url) and full_url not in visited:
                 to_visit.append(full_url)
 
     return pages
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 7</b></summary>

Why: The suggestion addresses a valid concern about potential infinite loops or excessive resource usage by limiting the number of pages to visit, enhancing performance and resource management.

</details></details></td><td align=center>7

</td></tr><tr><td>



<details><summary>Implement exponential backoff for <code>asyncio.sleep</code></summary>

___


**The <code>asyncio.sleep(5)</code> call should be replaced with a more dynamic backoff mechanism to <br>avoid unnecessary delays and improve responsiveness.**
    
[repo_copilot/github-integration/main.py [150]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-41baed3c80a361cce5655939ab39ae06a6d63d820e94d0e83ccdf10a4becd5e0R150-R150)

```diff
-await asyncio.sleep(5)
+await asyncio.sleep(5 * (2 ** attempt))
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 6</b></summary>

Why: The suggestion is valid and could improve performance by implementing a more dynamic backoff mechanism. However, the improvement is not critical and could be considered minor.

</details></details></td><td align=center>6

</td></tr><tr><td rowspan=1><strong>Enhancement</strong></td>
<td>



<details><summary>Modify <code>call_llm</code> to return only the response text, not the chunks</summary>

___


**The `call_llm` method should return the response text only, not the chunks.**
    
[repo_copilot/rag/issue/rag_app/llm_call.py [12-14]](https://github.com/valer1435/RepoPilot/pull/31/files#diff-1ab7e07eb1dbf31efaf9100515b2d7731a03bb9d45b90b5d033c2322d8a756b9R12-R14)

```diff
 def call_llm(self, query, chunks):
     return self.model.complete(
-        self.task_prompt.format(context='\n'.join([chunk.text for chunk in chunks]), query=query)).text, chunks
+        self.task_prompt.format(context='\n'.join([chunk.text for chunk in chunks]), query=query)).text
 
```
                   


<details><summary><b>Suggestion importance[1-10]: 6</b></summary>

Why: The suggestion improves the method's clarity by returning only the necessary response text, simplifying the method's output and reducing unnecessary data transfer.

</details></details></td><td align=center>6

</td></tr></tr></tbody></table>

**Comment by valer1435** [comment]
@RepoPilotAssistant /help

**Comment by RepoPilotAssistant** [comment]
## PR Agent Walkthrough 🤖

Welcome to the PR Agent, an AI-powered tool for automated pull request analysis, feedback, suggestions and more.

Here is a list of tools you can use to interact with the PR Agent:
<table><tr align='left'><th align='left'>Tool</th><th align='left'>Description</th><th align='left'>Trigger Interactively :gem:</th></tr>
<tr><td align='left'>

<strong>[DESCRIBE](https://pr-agent-docs.codium.ai/tools/describe/)</strong></td>
<td>Generates PR description - title, type, summary, code walkthrough and labels</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[REVIEW](https://pr-agent-docs.codium.ai/tools/review/)</strong></td>
<td>Adjustable feedback about the PR, possible issues, security concerns, review effort and more</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE](https://pr-agent-docs.codium.ai/tools/improve/)</strong></td>
<td>Code suggestions for improving the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[UPDATE CHANGELOG](https://pr-agent-docs.codium.ai/tools/update_changelog/)</strong></td>
<td>Automatically updates the changelog</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ADD DOCS](https://pr-agent-docs.codium.ai/tools/documentation/) 💎</strong></td>
<td>Generates documentation to methods/functions/classes that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[TEST](https://pr-agent-docs.codium.ai/tools/test/) 💎</strong></td>
<td>Generates unit tests for a specific component, based on the PR code change</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[IMPROVE COMPONENT](https://pr-agent-docs.codium.ai/tools/improve_component/) 💎</strong></td>
<td>Code suggestions for a specific component that changed in the PR</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ANALYZE](https://pr-agent-docs.codium.ai/tools/analyze/) 💎</strong></td>
<td>Identifies code components that changed in the PR, and enables to interactively generate tests, docs, and code suggestions for each component</td>
<td>

 - [ ] Run 
</td></tr>
<tr><td align='left'>

<strong>[ASK](https://pr-agent-docs.codium.ai/tools/ask/)</strong></td>
<td>Answering free-text questions about the PR</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[GENERATE CUSTOM LABELS](https://pr-agent-docs.codium.ai/tools/custom_labels/) 💎</strong></td>
<td>Generates custom labels for the PR, based on specific guidelines defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CI FEEDBACK](https://pr-agent-docs.codium.ai/tools/ci_feedback/) 💎</strong></td>
<td>Generates feedback and analysis for a failed CI job</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[CUSTOM PROMPT](https://pr-agent-docs.codium.ai/tools/custom_prompt/) 💎</strong></td>
<td>Generates custom suggestions for improving the PR code, derived only from a specific guidelines prompt defined by the user</td>
<td>

[*]
</td></tr>
<tr><td align='left'>

<strong>[SIMILAR ISSUE](https://pr-agent-docs.codium.ai/tools/similar_issues/)</strong></td>
<td>Automatically retrieves and presents similar issues</td>
<td>

[*]
</td></tr></table>



(1) Note that each tool be [triggered automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools-for-pr-actions) when a new PR is opened, or called manually by [commenting on a PR](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#online-usage).

(2) Tools marked with [*] require additional parameters to be passed. For example, to invoke the `/ask` tool, you need to comment on a PR: `/ask "<question content>"`. See the relevant documentation for each tool for more details.

**Comment by valer1435** [comment]
@RepoPilotAssistant /add_docs

**Comment by valer1435** [comment]
@RepoPilotAssistant /add_docs

**Comment by RepoPilotAssistant** [comment]
No code documentation found to improve this PR.

**Comment by valer1435** [comment]
@RepoPilotAssistant /analyze

**Pull request merged**
